### PR TITLE
Sync upstream changes

### PR DESCRIPTION
**Pull request by ChristopherFry**

### CODE REVIEW

**Comment by ChristopherFry** [comment]
This updates the UI to add support for the Porch resource version checks, https://github.com/GoogleContainerTools/kpt/pull/3993.

**Comment by johnbelamaric** [comment]
Thanks @ChristopherFry. If we merge this, will it cause problems with the existing Porch instances? That is, does it *need* the updated Porch, or now it just *works with* the updated Porch?

**Comment by ChristopherFry** [comment]
> Thanks @ChristopherFry. If we merge this, will it cause problems with the existing Porch instances? That is, does it need the updated Porch, or now it just works with the updated Porch?

Confirming this change is backwards compatible and works with existing Porch instances.

**Comment by johnbelamaric** [comment]
/approve
/lgtm

Thanks Chris. Now let's get the Porch PRs merged :)

**Pull request merged**
