### PR TITLE
Editors for Nephio-specific resources (1st batch).

### PR DESCRIPTION
**Pull request by kamilmadejek**
This PR adds three new editor UIs for resource types which are specific to Nephio:
- `infra.nephio.org/v1alpha1/WorkloadCluster`
- `infra.nephio.org/v1alpha1/Token`
- `req.nephio.org/v1alpha1/Capacity`

----

At this moment, the Web UI project does not support GUI editor functionality for any of Nephio-specific resource types. This PR is the beginning of a bigger effort which aims to close this gap and provide graphical editors for all relevant Nephio resources.

This PR follows previously established practices and editor creation conventions, which involve significant code repetition. Following PRs will aim to rework existing and new editors in a way which promotes code reuse and adheres to DRY principles.

----

image

_Example of `WorkloadCluster` editor._

----

Additional tweaks and fixes include:
- Added `LOCAL_PROXY` configuration mode, which makes it possible for WebUI developers to connect application to a Kubernetes proxy. SSH port forwarding can be used to easily connect to a remote cluster.
- Created `useSetStateAndCall` React hook which aims to limit undesirable usage of `useEffect` hook for reacting to state changes.

### CODE REVIEW

**Comment by kamilmadejek** [comment]
This time I'm publishing the PR from my private account (with linked Samsung email), so it seems I have to go through CLA authorization again. Hopefully it will be cleared soon.

**Comment by radoslawc** [comment]
Note to the reviewers and approvers: please ignore result of GitHub action: 'Generate Dependabot Configuration / run_python_script (pull_request)' it has no impact and status was added by error.

**Comment by kamilmadejek** [comment]
Hi @liamfallon @efiacor

I created this PR in an unfortunate moment, when it went unnoticed, buried beneath the avalanche of auto-generated Dependabot PRs 🙂

Now that we have this matter sorted out, I would be grateful if you could take a look at it.

**Comment by efiacor** [comment]
> Hi @liamfallon @efiacor
> 
> I created this PR in an unfortunate moment, when it went unnoticed, buried beneath the avalanche of auto-generated Dependabot PRs 🙂
> 
> Now that we have this matter sorted out, I would be grateful if you could take a look at it.

Hi @kamilmadejek , this looks interesting.
Would you have an easy way to deploy these changes so we can take a look?

**Comment by kamilmadejek** [comment]
Hi @efiacor, sure, I'll try to prepare this for Monday.

**Comment by kamilmadejek** [comment]
Hi @efiacor, I managed to prepare a Web UI deployment with these changes. I will share access details using a private channel.

The work done in this PR is quite rudimentary - it adds three relatively simple editors for Nephio-specific resources. These new editors are implemented in a similar way to already existing editors, thus they share their drawbacks (code duplication, some pre-existing bugs and quirks etc.). This PR serves mostly as my introduction into the topic.

I am currently prototyping a new approach for implementing editors, which aims to make their development more streamlined and code more maintainable.

**Pull request merged**
