### PR TITLE
Added PackageVarient Editor

### PR DESCRIPTION
**Pull request by chander12shekhar**
Added PackageVarient Editor

### CODE REVIEW

**Comment by ChristopherFry** [comment]
Thanks @chander12shekhar! This is looking nice.

I looked at the editor locally and have a few quick notes and suggestions. We'll want to do the first few items before merging the pull request, and the others can be deferred.

- The editor updates the 'packageContext.removeKeys' field as a string where the type is a string array, so this will need to be updated to format as an array of strings when saving this field (else the object will not be able to be applied to the cluster correctly)
- The editor also adds blank fields when opening and closing without making any changes. I noticed this while looking at the PackageVariants in the nephio-workload-cluster example package. Ideally, we want to avoid this.
- The Adoption and Deletion Policy are enums with just a few options for each, so suggesting we add a dropdown for these. This eliminates types and makes it a friendly user experience.
- The Upstream Package and Downstream Repository can be dropdowns as well. There are examples of each on the  AddPackagePackage. 
- Also, the accordion's title should be updated to show the package name for Upstream Package. Likewise, the Downstream Repository can show the repository. This allows anyone to quickly see what is selected without expanding the accordion.

**Comment by johnbelamaric** [comment]
> Thanks @chander12shekhar! This is looking nice. I left a few comments. We can merge this change once the comments are resolved.

Seems like the comments didn't come through?

**Comment by johnbelamaric** [comment]
/lgtm

Thanks, looking forward to having this in the UI!

**Pull request merged**
